spring:
  application:
    name: autenticacion
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eventpass_usuarios?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: ${SERVER_PORT:8083}
app:
  jwt:
    secret: ${JWT_SECRET:EventPassClaveDemostracionParaJWT2026_ClaveSegura}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
